### ISSUE TITLE
Persistent 2FA Storage

### ISSUE THREAD

**Issue by carTloyal123** [shauntarves/wyze-sdk#105]
Great library first of all. I am excited to try some of this with a hombridge plugin  to bridge the gap between cameras and devices using the wyze_docker repo.

My question is, can I persist my 2FA authentication between python sessions? At the moment, every time I re-run a test script, I also have to input my 2FA key which is fine but for instance in an automatic scenario where I restart  my application once a day this will become a bottleneck. Is there a way around this for testing and then deployment? I saw the refresh_token() method which could be useful but I am not sure if that helps in the case of shutting down the python app and restarting it. Thanks!

**Comment by shauntarves** [comment]
@carTloyal123 You have a few options here...

1. When you [create your `Client`](https://github.com/shauntarves/wyze-sdk/blob/master/wyze_sdk/api/client.py#L40-L57), pass in the `totp_code` for your 2FA (this is the code you first used to set up your 2FA app and is the seed for generating the 6 digits you use each time) and the library will automatically generate the 2FA for you, no human interaction needed.
2. Login once, **store the access token and refresh token somewhere**, and then use that refresh token to refresh the access token when you need it. This has the limitation that if you're trying to refresh after the refreshable window has expired, you'll need to reauthenticate.

Hope this helps!

**Comment by carTloyal123** [comment]
Hi @shauntarves 

Thank you for the quick response and again loving this repo. I will try both options as described so thank you!

**Comment by carTloyal123** [comment]
Question answered, thank you!

**Comment by carTloyal123** [comment]
@shauntarves Sorry to bring this back up, would you possibly be able to point me in the direction of where to get the access_token and refresh_token so that I can save them locally to use later? I ask this because I am working on a Hombridge plugin that will use wyze-sdk similar to RMCob's Wyze Vaccuum plugin but I would like to support 2FA without having to re-auth all the time. 

As far as I can tell, I have to reset my 2FA on my account in order to access a new TOTP code, is this correct?

Thanks again, great library!

**Comment by shauntarves** [comment]
hey @carTloyal123,

Let's start by clarifying a few things: a TOTP _code_ is what we generally call the 6 digits that you enter each time you want to log in and get prompted for the 2-factor code. The TOTP _key_ is the string of letters/numbers that you put into your authenticator app to generate those codes.

I mis-typed in my response above, which should have read "pass in the `totp_key`...". There are many ways to get your TOTP key if you don't have it. You're correct that one of the backup codes should work, but you can likely also get your key out of your existing authenticator app.

Internally, the `client` object stores the `access_token` and `refresh_token` after it is created and the client logs in. You can see them by doing something like:
```
client = wyze_sdk.Client(email=xxxx, password=xxxx)
print(client._token)
print(client._refresh_token)
```

When you are creating your client, you can provide the `totp_key` from above and the library _should_ automatically handle the 2FA auth without user interaction:
```
client = wyze_sdk.Client(email=xxxx, password=xxxx, totp_key=xxxx)
```

So, a simple flow could be something like:
1. Create the client (with the `totp_key` if the account has 2FA enabled)
2. Store the `token` and `refresh_token`
3. Periodically call `client.refresh_token()` to refresh the token as needed.

Right now, this library doesn't support creating a client and using stored token/refresh_token. When you make a client, you must provide the email/password and the `client.login()` method is called during creation. If your use case would be helped by being able to create a client object with a token/refresh_token and optionally _not_ login (remember that "login" means exchange the email/password for a token), I can add that functionality pretty easily.

Please let me know what you think.

**Comment by carTloyal123** [comment]
Update: I also frequently get an issue as shown below which I am also hoping to resolve using the stored token method of some kind.

~~~
Error: The server responded with: {'description': 'Too many failed attempts. Please try again later.', 'requestId': '2462c49e-b936-4124-8c59-cadf65720ea8', 'errorCode': 1000}
~~~

This seems to be a cooldown of some kind on the Wyze side resulting from logging in too many times or killing the python script before logins complete. I am not sure the final cause but I am looking for ways to avoid this issue.

**Comment by Sfrjoshpro** [comment]
I had the same issues. I had to initiate client then pass the object

**Comment by carTloyal123** [comment]
A solution very similar to what has been done here:
https://github.com/jfarmer08/homebridge-wyze-smart-home/blob/65059d19b9c800f11546ba2f07ac270ab2ee6dc9/src/WyzeAPI.js#L206

Just writing to persistent storage and checking if that token is available from storage, otherwise login as normal. I am going to take a crack at a rough implementation to see if I can get it working then come back once there is more to share.

**Comment by carTloyal123** [comment]
When I have time, I will write a PR  for  this feature, but no need to keep this issue open unless @shauntarves has some input on how  to proceed. Thanks!
