### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Sfrjoshpro** [shauntarves/wyze-sdk#109]
Can we have a Auto update on the token when it need refresh?

**Comment by shauntarves** [comment]
Hey @Sfrjoshpro, that's probably something that would be coded at the "application" level, not at this library level. I would have to play around with the code a bit to see if I can extract the access token expiration date from the access token and provide that as part of the client object.

The client already has a `refresh_token()` method, but it must be called manually. Please also see my comment [here](https://github.com/shauntarves/wyze-sdk/issues/105#issuecomment-1329309111) about adding support for initializing a client without doing a login. That might be the best approach but I'd need to add that ability.

Let me know what you think

**Comment by Sfrjoshpro** [comment]
Ok I’ll play with it. I was trying to play with the refresh option but i
struggled, I’ll put more time into it. 😊

**Comment by Sfrjoshpro** [comment]
Going to let this run think it should work. 🫣    Really appreciate you being so humble, I do this just for hobby/need know enough to get in trouble some could argue. But I learn more every day. Really appreciate everything. 

Been looking at the wrapper code it's inspiring

**Comment by shauntarves** [comment]
Let me know how this goes. It looks like a reasonable approach.

As part of that other 2FA issue, I'm going to spend a bit more time investigating the auth pattern and there will definitely be some changes. First, it should be easy enough to add some more smarts about the token - like when it expires. Then I'll probably add some ability to configure the client with a token and perform refresh or login if the token is expired.

This is all really great feedback and I'm excited to make the library more usable for everyone!

**Comment by Sfrjoshpro** [comment]
So it ran all night and was still running. So it seems like this approach is definitely working for the time being. 

I'm going to dig more into the sdk, to understand more how the back end works. Thanks

**Comment by shauntarves** [comment]
I would say don't try to add anything new at the moment. I've already started work on improving some of these auth/client issues. Give me the weekend and hopefully I'll have something for you on Monday.

**Comment by Sfrjoshpro** [comment]
Sounds good, thanks!
