### ISSUE TITLE
Camera Streams?

### ISSUE THREAD

**Issue by wesbos** [shauntarves/wyze-sdk#11]
Apologies if this is in the docs, but from skimming the code it doesn't support getting access to the camera's events, or live video stream, does it? Been loking for a way to do this forever, and I've always come up empty handed

**Comment by romedtino** [comment]
Not sure about camera events but for live video/stream you actually have three options I know of right now

1. [WyzeHacks](https://github.com/HclX/WyzeHacks) + [WyzeCameraLiveStream](https://github.com/FiveLeavesLeft/WyzeCameraLiveStream) which works on any Wyze camera that can run WyzeHacks. (I currently have it running with a v2 and a v3 attached to [HomeAssistant](https://www.home-assistant.io/) [Frigate](https://github.com/blakeblackshear/frigate) ). It's not perfect but you get a working RTSP stream (the camera drops out and comes back in 30 sec every few hours)
2. [DafangHacks](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks) Works decently well but you usually get stuck at a lower firmware version on the cameras. 
3. Official beta RTSP firmware from Wyze - Only available for v2 and Pan, also stuck at a certain firmware version

Someone correct me if I am wrong but I think the API exposes the data stream for the live video but you would need something else to decode the stream to an actual video [as the TinyCam dev describes here](https://github.com/nblavoie/wyzecam-api/blob/master/wyzecam-protocol/ProtocolWyzecam.java)

**Comment by shauntarves** [comment]
You can get camera events through the `client.events` code in this library.

There is no way I have found to give you access to the camera stream. The
native codec wyze cameras use is only supported via a java library (which
is available in various places online). I have seen other projects that
have attempted to model the data protocol, and they may have been
successful, but I don't know for sure.

**Comment by wesbos** [comment]
Thanks everyone, I'm not looking to do RTSP, so I'll search for those Java libs. If anyone knows of them please post below

**Comment by shauntarves** [comment]
@wesbos https://github.com/cnping/TUTK

This is the library that is used in TinyCam and other non-official Wyze api packages people are using. Again, I've only ever seen TUTK codec libraries in Java (and believe me, I looked for others). I suppose someone could fairly easily port it to python or some other language if desired. Unfortunately, this is like a 10-year-old proprietary format that the WyzeCams are using.

**Comment by kroo** [comment]
I was able to pick up where the folks at [wyzecam-api](https://github.com/nblavoie/wyzecam-api) left off, and built a little library around accessing the streaming video here: [kroo/wyzecam](https://github.com/)

**Comment by wesbos** [comment]
Looks like Wyze is swtiching to WebRTC. No leads on how to access it yet, but if anyone finds out info let me know! 

<img width="602" alt="Screen Shot 2021-06-01 at 3 00 39 PM" src="https://user-images.githubusercontent.com/176013/120377060-9dc4fa80-c2ea-11eb-8419-46aedab752e6.png">
