### ISSUE TITLE
[REQUEST] Help with API Endpoints

### ISSUE THREAD

**Issue by carTloyal123** [shauntarves/wyze-sdk#124]
@shauntarves I was wondering if you would be open to sharing how you have profiled and determined the Wyze API endpoints and network calls. I am trying to get the Wyze Video Doorbell Pro to stream locally or at least be viewable outside the app and was wondering if you might be able to assist. It seems like the camera operates on the new mars API endpoints which deal with some of the new cameras. Do you have some profiling or detection methods for what those calls look like and how to determine the endpoints?

**Comment by carTloyal123** [comment]
I am also working on a mars client using your base classes and was wondering how you are generating the wyze salts? I think the mars endpoints need the signature2 which is generated with the specific appid. If I have traced it correctly it looks like you have hard coded the signing secret for the base app and the venus service. Would you know how to find the mars secret as well? @shauntarves

**Comment by shauntarves** [comment]
Hey @carTloyal123, this is probably easier to take into email/imessage. Please email me at `shaun <at> tarves <dot> net` and we can chat.

**Comment by wmoss** [comment]
I'm also very interested in learning about this as I'd like to possibly contribute some for some new devices as well. Shaun, I'll email you and if you can copy me in that would be great.
