### ISSUE TITLE
S Scale Latest Records not returning records

### ISSUE THREAD

**Issue by aaronsmith1234** [shauntarves/wyze-sdk#125]
Hi @shauntarves, as discussed [here](https://github.com/shauntarves/wyze-sdk/issues/113), seeing a weird issue with the s scale and not returning latest records. Happy to help however I can! One idea: we validated that `client.scales.get_records(device_model=model, start_time=start_time, end_time=end_time)` does return records, so maybe its a simple as for the scale, overriding the latest_records attribute to be pulling that data instead? Again, happy to help however I can!

**Comment by shauntarves** [comment]
Hi @aaronsmith1234, could you please try with the referenced branch (https://github.com/shauntarves/wyze-sdk/tree/125-s-scale-latest-records-not-returning-records). I believe it is fixed now. If you confirm that it looks good, I'll create a new patch release.

**Comment by aaronsmith1234** [comment]
Thanks! I am currently on vacation but will take a look when I get back. I
gave it a shot a few minutes ago but don't know last time my scale synced.

**Comment by aaronsmith1234** [comment]
@shauntarves i can confirm that this branch fixes the issue; records returned successfully. Thanks!

**Comment by aaronsmith1234** [comment]
Hey @shauntarves  just following up; can confirm that branch fixes the issue
