### ISSUE TITLE
Unknown device type detected: Outdoor camera base station

### ISSUE THREAD

**Issue by jsrober** [shauntarves/wyze-sdk#13]
Unknown device type detected ({'mac': 'x', 'first_activation_ts': x, 'first_binding_ts': x, 'enr': 'x', 'nickname': 'Outdoor Base 2 Back', 'timezone_name': 'America/New_York', 'product_model': 'WVODB1', 'product_model_logo_url': 'https://s3-us-west-2.amazonaws.com/wyze-file/system-logo/device/small/wyze_icon_device_wvodb1.png', 'product_type': 'BaseStation', 'hardware_ver': '0.0.0.2', 'firmware_ver': '4.16.1.22', 'user_role': 1, 'binding_user_nickname': 'x@x.com', 'conn_state': 1, 'conn_state_ts': x, 'push_switch': 1, 'device_params': {'p2p_id': 'x', 'p2p_type': 3, 'ssid': '', 'ip': '192.168.123.161', 'power_switch': 1, 'temperature': '0', 'humidity': '0', 'temp_humi_room_type': 1, 'comfort_standard_level': 2, 'is_temperature_humidity': '0', 'records_event_switch': 0, 'motion_alarm_switch': 1, 'audio_alarm_switch': 0, 'smoke_alarm_switch': 0, 'co_alarm_switch': 0, 'electricity': '100', 'battery_charging_status': '0', 'is_link_toy_car': 0, 'power_saving_mode_switch': 0, 'camera_thumbnails': {'thumbnails_url': None, 'thumbnails_ts': 0}}, 'is_in_auto': 0, 'event_master_switch': 1, 'parent_device_mac': '', 'parent_device_enr': '', 'binding_ts': x, 'timezone_gmt_offset': -4.0})

**Comment by shauntarves** [comment]
@jsrober I'm not familiar with the base station, but I don't think there's much we can do with it. I'll add basic support for getting power state, ip, etc in the next minor release.

If you know of any actions you can take on the base station you want supported, let me know.

**Comment by shauntarves** [comment]
Added basic support in v1.1.4 - will just parse the object details.

If there are other features that make sense to add, open another issue and I'll work on them.
