### ISSUE TITLE
error when interacting with locks

### ISSUE THREAD

**Issue by Ronald-TR** [shauntarves/wyze-sdk#139]
When i try to call any method from locks i get a side effect error like "None is not iterable", but inspecting the API output, i'm receiving this:
```
{
    "ReqID": "99d7c451c5",
    "ErrNo": "14008",
    "ErrMsg": "PARAM_SIGN_INVALID"
}
```

Can someone help me to understand it? I tried to generate other values for the "sign" param but without success.

**Comment by Ronald-TR** [comment]
The locker that I'm using is Wyze Lock Bolt. I saw that this locker only uses bluetooth to comunicate with the wyze app.
Can someone tell me if is possible to integrate with this locker?

**Comment by shauntarves** [comment]
Hi @Ronald-TR,

I've developed this against the Wyze Lock product. If the Wyze Lock Bolt is not wi-fi enabled (bluetooth only), then I doubt it will work with a client like this. This client basically mimics that http requests made by the Wyze app, but it cannot mimic proximity or near-field protocol like bluetooth 😢
