### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Sfrjoshpro** [shauntarves/wyze-sdk#141]
Code been same for months saw them talking about changing there auth. Did api get locked out?!

**Comment by Sfrjoshpro** [comment]
None type object not subscribable. If response 
['action_token']

**Comment by Sfrjoshpro** [comment]
https://support.wyze.com/hc/en-us/articles/16129834216731-Creating-an-API-Key

**Comment by JohnMTorgerson** [comment]
I noticed there's an API key hard-coded in auth_service.py. I wonder if it didn't just expire today. Presumably we should all be generating our own API keys and the SDK should ask us for it, rather than everyone using Shaun's?

**Comment by mrlt8** [comment]
I submitted a PR for the new auth API endpoint a couple of weeks ago #140.

**Comment by JohnMTorgerson** [comment]
> I submitted a PR for the new auth API endpoint a couple of weeks ago #140.

Oh sweet, thanks! At least I can fork that and use it locally until it's accepted.

**Comment by Sfrjoshpro** [comment]
Noted thanks I'll give thst a shot

**Comment by samrossporta** [comment]
Any timeline on when #140 will be merged with master?

**Comment by shauntarves** [comment]
hey guys...sorry for delay here - I'm not able to keep up with this repo much these days.

1. That API key that's hard-coded isn't mine at all - it's something I dug out of the app and was needed for calling the auth service to login.
2. I will test out the patch today and get it merged

**Comment by Sfrjoshpro** [comment]
Look forward to hearing how it goes. And thank god for mrlt8 for the patch.
   Will say since it’s a big part of my set up I need to learn more about
how it work so if it breaks. Or what not

**Comment by JohnMTorgerson** [comment]
> 1. That API key that's hard-coded isn't mine at all - it's something I dug out of the app and was needed for calling the auth service to login.

Oh interesting. Anyway, thanks for getting that merged. And thanks to [mrlt8](https://github.com/mrlt8) for the patch!

**Comment by Sfrjoshpro** [comment]
Yea my garden humidifier and dehumidifier and irrigation work on this. 😅 did it get merged

**Comment by H8Houston** [comment]
Having the same issue and looking forward to the merge.  I am not a very proficient python coder.  Once it is merged, how do I get the merge implemented into the wyze-sdk on my linux host?  Can i just run a 'pip install wyze-sdk' command again or do I need to do something fancier than that?

**Comment by Sfrjoshpro** [comment]
Once it hits the masters you just gotta update your STK and then you should be good

**Comment by shauntarves** [comment]
Hey folks...just published v2.0.0 thanks to @mrlt8's contribution. You will need to generate the API key on Wyze's site and feed it into the client constructor in order to login and create the new access token.

I'm honored that so many folks rely on this to control their homes - that's a lot of pressure 🤣

**Comment by romedtino** [comment]
That's what happens when you provide an _amazing_ service and filling a hole Wyze has yet to fill :P. Definitely appreciate this!

**Comment by H8Houston** [comment]
@shauntarves  & @mrlt8:  Y'all rock!  Thanks for the update. Everything back to normal.  Happy me, happy mom, happy life!  Wyze bulbs once again working and responding to weather conditions outside.  Christmas in July! Thank you.
