### ISSUE TITLE
Handling unsupported devices

### ISSUE THREAD

**Issue by Soups71** [shauntarves/wyze-sdk#143]
I was working with devices that were not supported directly by the SDK. The SDK accurately detected these devices, but from what I could tell the SDK does not store any of the details specific to the unknown device. If this is something that is a desired feature, I'd be willing to work on finding a way to retain the additional device information not currently stored.

**Comment by shauntarves** [comment]
Hey @Soups71,

I'm not sure what your desired behavior is, but - in general - before I've added any kind of specific support for the device type, I exclude it from the processing/parsing into a python object and just report that in the log.

"support" in this case just means that the SDK can know some basic amount of information about the device, like what kind of thing it is.
