### ISSUE TITLE
client.events.list()[x].to_dict() returns empty set

### ISSUE THREAD

**Issue by gloriouslyawkward** [shauntarves/wyze-sdk#145]
`events = client.events.list()`
`event[0]._to_dict()` returns `{}` (event[any number] returns `{}`

**Comment by shauntarves** [comment]
Is this still an issue for you? Keep in mind that wyze only stores/shows events from the past 14 days.

Also, you'll want to use `event[xxxx].to_dict()`, not `_to_dict()`

**Comment by MrRenter** [comment]
I have this same issue. I have two cameras and a scale. There are 20 events returned all returning {}. I have 12 actual events in the last hour in my app from one camera. I would like to pull the last 3 times an event happened and retrieve the date time and camera. 

```
client = Client().login(email='redacted, password='redacted', api_key='redacted', key_id='redacted')
client2 = Client(token=client['access_token'])

response = client2.events.list()

for item in response:
    print(item.to_dict())
    print("\n")
```
