### ISSUE TITLE
events.list not executing properly

### ISSUE THREAD

**Issue by liamhoganson** [shauntarves/wyze-sdk#149]
When trying to execute:
`response = client.events.list(event_values= "[EventAlarmType.MOTION]")`

I'm getting this error:
`    kwargs.update({"event_value_list": [code for code in event_values.codes]})
AttributeError: 'str' object has no attribute 'codes'`

**Comment by shauntarves** [comment]
Hi @liamhoganson, this isn't the correct syntax for the command you're trying to execute. You have the quotes in the wrong place. It should be:

```
from wyze_sdk.models.events import EventAlarmType
...
response = client.events.list(event_values= [EventAlarmType.MOTION])
```
