### ISSUE TITLE
Incorrect IP address for Wyze Plug Outdoor

### ISSUE THREAD

**Issue by dmtucker** [shauntarves/wyze-sdk#153]
It looks like the subnet is correct, so the address could have been accurate at one point.
I've never seen a different address show up since I started using this SDK a couple weeks ago.

- This applies to the parent device as well as both sockets.
- The same info is returned in `devices_list` as well as `client.plugs.info`.

**Comment by shauntarves** [comment]
Hey @dmtucker I don't know how to reproduce this. When I compare what I see for my own outdoor plug via the SDK against what's in the Wyze app, there's no difference.

Are you still seeing an issue here?

**Comment by dmtucker** [comment]
I am not, and I don't know of a way to force a repro. I'll reopen if that changes!
