### ISSUE TITLE
ModuleNotFoundError: No module named 'wyze_sdk'

### ISSUE THREAD

**Issue by drakehomebridge** [shauntarves/wyze-sdk#169]
Installed this [plugin](https://github.com/RMCob/homebridge-wyze-robovac) on my M1 Mac mini. I am getting the following error. 

`error: Command failed: python3 /usr/local/lib/node_modules/homebridge-wyze-robovac/py_helpers/getVacuumDeviceList.py 
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/homebridge-wyze-robovac/py_helpers/getVacuumDeviceList.py", line 4, in <module>
    import wyze_sdk
ModuleNotFoundError: No module named 'wyze_sdk'`

I ran `Pip install wyze_sdk` and it has been successfully installed. Python3 is fully up-to-date along with the Node.js.

**Comment by shauntarves** [comment]
This is a question for the developers of `homebridge-wyze-robovac`
