### ISSUE TITLE
Calling the client won't let me login

### ISSUE THREAD

**Issue by feliutg** [shauntarves/wyze-sdk#35]
Seems something changed because I have an automation that log in automatically in my account and it stopped working. The password is fine and I can use the Wyze application as normal. Probably an API changed?

**Comment by JohnMTorgerson** [comment]
Same.

```
2021-07-22 18:40:05,114 : ERROR : main : WyzeApiError retrieving bulbs: Parameters passed to Wyze Service do not fit the endpoint
The server responded with: {'ts': 1626997204144, 'code': '1001', 'msg': 'ParameterError', 'data': {}}

```

**Comment by taylorbernt0** [comment]
Same here. I've been using the same username and password and these are the headers that wyze_sdk is receiving after trying to login now:

`{'Content-Type': 'application/json', 'Content-Length': '36', 'Connection': 'keep-alive', 'Date': 'Thu, 22 Jul 2021 23:54:21 GMT', 'x-amzn-RequestId': '689d8a8b-982e-4779-bfd8-0ca49dbd5cbe', 'x-amzn-ErrorType': 'ForbiddenException', 'x-amz-apigw-id': 'C5W_KEGBvHcFprg=', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 0fdea8d3b1fc76e3ff9d36e8164171e9.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'DEN52-C1', 'X-Amz-Cf-Id': 'AxGs1exqE4J9bm4K1fBLfXFHXWNMDHoiMMgYdG5qzknPXqYgVXbR7Q=='}`

**Comment by taylorbernt0** [comment]
I found a temporary solution! Adding a user-agent header to the _get_headers function in auth_service.py works.
Example:
```
request_specific_headers.update({
            "user-agent": "wyze_android_2.11.40",   <----- This is the line to add
            'x-api-key': self.api_key,
})
```

**Comment by shauntarves** [comment]
Okay. I will take a look in the morning.

I have quite the backlog of things to address here :)

**Comment by Antyos** [comment]
Thanks for the fix @taylorbernt0! I think I remember Wyze sent out an email a few weeks ago noting that they were dropping compatibility for older versions of their app for security reasons. Because of that, it would make sense that this small fix is the correct solution.

**Comment by JohnMTorgerson** [comment]
Thanks @taylorbernt0 that worked for me too, even though I don't understand a lick of what's going on there.

**Comment by TheGreatSkeeve** [comment]
Big thanks to @taylorbernt0 for that fix!  That did the trick, I'm super excited to check out this client.  Just bought so much Wyze stuff.

**Comment by shauntarves** [comment]
Hey all...I will get a permanent fix in for this shortly. I've got a handful of fixes piling up, just need a bit of time to work them.

**Comment by NewMountain** [comment]
@taylorbernt0 Totally worked for me as well. Thank you so much!
