### ISSUE TITLE
Cancel cleaning vs. dock for vacuum

### ISSUE THREAD

**Issue by bdwilson** [shauntarves/wyze-sdk#36]
More of a feature request, but if the vacuum returns to the dock to charge during a cleaning, there doesn't appear to be a way to cancel that cleaning via wyze-sdk.  If dock is called, it's already docked so nothing is done.  In the app, if you hit stop, it will cancel the cleaning routine (i.e. it won't pick back up where it left off after reaching 20% charge).  Hoping this is something that can be added. 
![IMG_2062](https://user-images.githubusercontent.com/317946/127008876-db1980c8-e07f-42ce-b109-df4ed2271669.jpeg)
![IMG_2063](https://user-images.githubusercontent.com/317946/127008892-6af55783-497a-47cf-b293-7365d01ca06e.jpeg)

**Comment by shauntarves** [comment]
Hey @bdwilson,

Good catch - this is just an oversight on my part. I am finally planning to implement some fixes that have been piling up, so I will include this.

**Comment by shauntarves** [comment]
@bdwilson @alanjames1987

Sorry for the super-long delay on this. But, I finally had some time to revamp the vacuum controls to the newer style the apps are using. The branch https://github.com/shauntarves/wyze-sdk/tree/36-cancel-cleaning-vs-dock-for-vacuum has support for clean/pause/dock/stop.

There are several conditions that is handled by "stop":
- when a vac is on its way to recharge because a user told it to dock, stop its motion
- when a vac is on its way to recharge because it finished cleaning and is returning home, stop its motion
- when a vac has to charge because it ran out of power during cleaning, if it hasn't yet made it to the dock, stop its motion
- when a vac has to charge because it ran out of power during cleaning, **and it's already on the dock**, stop/cancel the cleaning program

Since this functionality is kind of overloaded, I'm happy to add a separate "cancel" command that can be run for the last bullet point scenario if you want. I just followed how the code in the app worked to implement what's there now...it's easy enough to separate out the actions.

**Comment by bdwilson** [comment]
Thanks for your continued work on this! I use this integration daily! I think my use case would use the "cancel" option (last bullet) if it was a separate action. The only issues I have today is when there isn't enough battery to finish a job, it goes home to charge, someone arrives home (which sends dock command), but it's on the dock already charging), then when the wife is cooking dinner it pops out and decides to finish the job. 😃 cancel would end the job even if battery was enough to finish.

**Comment by shauntarves** [comment]
@bdwilson just pushed up changes that split the cancel and stop functionality and made "clean" either start or resume based on current state. Here's how the actions work:

* `clean` - starts a cleaning OR resumes a cleaning if the vac was paused mid-clean
* `pause` - pauses the vac while it's cleaning
* `dock` - cancels the current cleaning and returns the vac to the dock
* `stop` - the first 2 bullets above - is only relevant when the vac is on its way back to the charging station to charge
* `cancel` - prevents the vacuum from resuming an unfinished cleaning action after charging <-- this is what you were looking for

If you're able to test this out a bit, that would be great. It would be good to get another set of eyes before I merge and release. But, if you're not able to, just let me know and I'll go ahead with it.

**Comment by bdwilson** [comment]
I will be home Sunday. I may be able to test remotely. Will let you know! Thanks again!

**Comment by bdwilson** [comment]
So I gave it a whirl tonight.  I was unable to cancel if it was cleaning. 

wyze_sdk.errors.WyzeRequestError: Device cleaning cannot be canceled when in VacuumMode.CLEANING. Docking may be possible.

Then I sent it to charge (dock command), and tried to immediately cancel.
wyze_sdk.errors.WyzeRequestError: Device cleaning cannot be canceled when in VacuumMode.RETURNING_TO_CHARGE. Docking may be possible.

When it finished docking, I attempted to cancel, and got this. 
(cancel was called with the same args as dock and clean):

`			client.vacuums.cancel(device_mac=device,device_model=vacuum.product.model)
`
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/code/wyzevac-api/wyzevac_flask.py", line 108, in api
    val = sendCommand(device,command,rooms)
  File "/code/wyzevac-api/wyzevac_flask.py", line 69, in sendCommand
    vacuum = client.vacuums.info(device_mac=device)
  File "/code/wyze-sdk/wyze_sdk/api/devices/vacuums.py", line 40, in info
    iot_prop = super()._venus_client().get_iot_prop(did=device_mac, keys=[prop_def.pid for prop_def in Vacuum.props().values()])
  File "/code/wyze-sdk/wyze_sdk/service/venus_service.py", line 159, in get_iot_prop
    return self.api_call('/plugin/venus/get_iot_prop', http_verb="GET", params=kwargs)
  File "/code/wyze-sdk/wyze_sdk/service/venus_service.py", line 40, in api_call
    return super().api_call(
  File "/code/wyze-sdk/wyze_sdk/service/base.py", line 339, in api_call
    return super().api_call(
  File "/code/wyze-sdk/wyze_sdk/service/base.py", line 198, in api_call
    return self.do_get(url=api_url, headers=headers, payload=params)
  File "/code/wyze-sdk/wyze_sdk/service/base.py", line 143, in do_get
    return self._do_request(client, req)
  File "/code/wyze-sdk/wyze_sdk/service/base.py", line 93, in _do_request
    return WyzeResponse(
  File "/code/wyze-sdk/wyze_sdk/service/wyze_response.py", line 142, in validate
    raise e.WyzeApiError(message, self.data)
wyze_sdk.errors.WyzeApiError: The request to the Wyze API failed.
The server responded with: {'code': 2001, 'current': 0, 'hash': '1', 'instance_id': 'f25ab6465ce9d0e5a50d7e3d57c7317b', 'isShowToast': 0, 'message': 'Access token error', 'total': 0, 'version': 1}
```
From looking at your code, it looks like the goal of 'cancel' was to dock & cancel.  Perhaps I'm just reading it wrong :)

**Comment by shauntarves** [comment]
Unfortunately, cancel is only used to stop an unfinished cleaning when the
device has returned to charge.

Dock is the correct command to return the vacuum to the dock. Then you
could issue a "stop" to literally stop the vacuum where it is or a "clean"
to resume the cleaning process.

I just rebased this branch off master, which has a few new changes, so
maybe give it another try. Let me know if you still have issues.

- Shaun

**Comment by bdwilson** [comment]
Seemed to work tonight. Sent it to clean with 21% left, battery ran low, it went home on its own.  Then I issued cancel. No errors returned, but it did say something like "return stopped" (sorry, I should have written it down).   I'll see if it wakes up on its own later and starts to phantom clean.

**Comment by bdwilson** [comment]
@shauntarves looking good on my end!
