### ISSUE TITLE
Control door lock pincode via API

### ISSUE THREAD

**Issue by softlogix-io** [shauntarves/wyze-sdk#39]
Hello,
I'm looking to control the pincode for the door lock over the web. I want to be able to automate the creation and removal of pins programmatically.
Thank you.

**Comment by SpringStStays** [comment]
I second this! I really would love this :)

**Comment by shauntarves** [comment]
This functionality (and more!) has been added in https://github.com/shauntarves/wyze-sdk/releases/tag/v1.6.0

Please see the [PR comment](https://github.com/shauntarves/wyze-sdk/pull/95#issue-1409539329) for example code to display and control the access keys
