### ISSUE TITLE
Any way to expose whether a mesh bulb is currently displaying color or white?

### ISSUE THREAD

**Issue by JohnMTorgerson** [shauntarves/wyze-sdk#41]
I haven't been able to find anything in the provided bulb info that indicates whether a mesh bulb is currently in color mode or white mode. Wondering if there's anything the bulb can give you that would allow you to expose it via the API? It's something that would be useful to know for my application, if it's possible to do.

**Comment by shauntarves** [comment]
Hi John,

The mesh/color bulb has 2 fields related to color: temperature and color.
The logic in the Wyze app appears to toggle whether the bulb is in white or
color mode based on whether the temperature property is set and non-zero.
Give that a shot?

**Comment by JohnMTorgerson** [comment]
Hey, thanks for getting back to me, sorry about the delay responding to you. The python API seems to report the last used temperature and the last used color setting for each bulb regardless of which mode it is currently in, so it seems there's no way (currently) to tell which. Is it perhaps the case that the bulb itself is updating/erasing the temperature value when put into color mode but the API just isn't picking up on it somehow? Although I'm not sure how it would remember what the last value was if it isn't getting the info from the bulb every time...

**Comment by shauntarves** [comment]
This has been added as a new field in `Bulb` called `control_mode` (https://github.com/shauntarves/wyze-sdk/blob/master/wyze_sdk/models/devices/lights.py#L159) and is backed by a new enum `LightControlMode` (https://github.com/shauntarves/wyze-sdk/blob/master/wyze_sdk/models/devices/lights.py#L11-L31)
