### ISSUE TITLE
Thermostat lock state update does not reflect in mobile application.

### ISSUE THREAD

**Issue by Usama-Aslam23** [shauntarves/wyze-sdk#42]
When we set thermostat lock state using the API it goes through fine and updates the key in info as well but same does not reflect on mobile application.

**Comment by shauntarves** [comment]
Hey @Usama-Aslam23, sorry it has taken me so long to address this. I do t currently have a thermostat, but if you'd be willing to share yours with me via the app, I can take a look and fix this.

Let me know!

**Comment by shauntarves** [comment]
Fixed
