### ISSUE TITLE
Two issues with 1.2.2

### ISSUE THREAD

**Issue by kwpodolsky** [shauntarves/wyze-sdk#43]
Version.py references 1.2.1, not, 1.2.2
Everytime I connect to the Wyze service I get hit with the Enter Wyze SMS 2FA Verification Code, which requires manually entereing the code sent via SMS, into the running app.
Is there a way to either disable the 2FA requirment or maybe create an authentication certificate to avoid this?
Is that possible?

**Comment by shauntarves** [comment]
Hi @kwpodolsky, sorry for the delayed response.

I'll fix the version.py thing in the next release. Thanks for letting me know.

As for the 2FA code, there is support for using a TOTP key, which will allow you to keep 2FA enabled, but not have to type in a code every time. I haven't added it to the docs yet apparently, but it's there! Something like this will work:

```
client = Client(email=os.environ['WYZE_EMAIL'], password=os.environ['WYZE_PASSWORD'], totp="abcdef1234567890")
```

See https://github.com/shauntarves/wyze-sdk/pull/22 for further info
