### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by wkrasner** [shauntarves/wyze-sdk#45]
Hi  I downloaded the python sdk as per instruction when I execute the routine to get a list of devices it looks like I am having an authentication issue.  The error is as follows:

Traceback (most recent call last):
  File "P:\wyze2.py", line 5, in <module>
    client = Client(email=os.environ['xxx@gmail.com'], password=os.environ['xxxx'])
  File "c:\python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'xxxxxxxx@gmail.com

I am using my wyze credentials for email=os.environ and  password=os.environ

 Any thoughts

Thanks

Will

**Comment by shauntarves** [comment]
Hi Will,

That’s not how the environment variables work. If you are t familiar with
using them, please just use Client(email=<your email>, password=<your
password>).

Also, please change your password now that you’ve put it here so your
account doesn’t end up compromised.

**Comment by wkrasner** [comment]
Thank you.  I missed the password in the post.  I appreciate the heads up.  I have never used the environment variables in python before,  but looked up how to use them.  I assuming I have to set the environment variables to my wyze credentials.  I did that and still get the same error.  My aplogies I am new to python.  

Will

**Comment by shauntarves** [comment]
Depending on whether you use Windows or Mac/Linux, the process is a bit different.

If you were using a Unix-type machine and working in a Terminal shell, you'd do something like:
```
export USERNAME="my_username"
export PASSWORD="my_password"
```
to set the variables. Then, your python code would reference them by the key(s) you used when setting:

```
os.environ['USERNAME']
os.environ['PASSWORD']
```

There's not much advantage to using the environment variable approach if you're just writing a script or something for yourself to use, it might be better to just put the username and password in strings directly in the call to create the new Client.

**Comment by wkrasner** [comment]
Shaun

 Thank you very much I did actually take your suggestion of the latter and
it works perfectly. I was curious where I could find some syntactic support
for the actually controlling the vacuums.

Thank you again

Will

**Comment by zvarnes** [comment]
@shauntarves I'm using the test script which sets the environment variables when run and I'm still getting this error. It's unclear to me how to resolve this
