### ISSUE TITLE
Vacuum and Rooms

### ISSUE THREAD

**Issue by wkrasner** [shauntarves/wyze-sdk#46]
First  I want to thank you for putting this project together.  I am able to get the vacuum to vacuum a specific room based on the syntax you posted.  Is there anyway to just have it sweep all rooms on the map?

Thanks 

Will

**Comment by shauntarves** [comment]
Hey @wkrasner,

I'm not sure what happened to the doc generation, but it appears busted now. I'll take a look at that. The short answer is, of course you can!

```
client.vacuums.clean(device_mac='xxxx', device_model='xxx')
client.vacuums.pause(device_mac='xxxx', device_model='xxx')
client.vacuums.dock(device_mac='xxxx', device_model='xxx')
```

**Comment by wkrasner** [comment]
Thank you  .  Works great!
