### ISSUE TITLE
Are there any plans to control the Wyze Car?

### ISSUE THREAD

**Issue by JoshuaMorris** [shauntarves/wyze-sdk#47]
I'm exploring options to control the Wyze Car using a raspberryPI running between the Camera using the RTSP firmware and Car. Looking into what options are available what insight or suggestions you might have to offer based on your experience

**Comment by shauntarves** [comment]
hey @JoshuaMorris, this sounds like a fantastically fun project. Hit me up by email shaun <at> tarves "dot" net and we can chat some more about what it will take

**Comment by MysticNynja** [comment]
Was this enhancement made? I'm not seeing anything in the repo for a car type

**Comment by shauntarves** [comment]
No, not yet. I’m struggling to understand what kind of use case there would
be for controlling the car this way. Happy to have any suggestions and I
can put it on my radar for sure!

**Comment by JoshuaMorris** [comment]
I want to control the car from the pi to automate the car to drive around my yard to chase animals out of my garden and to use it as a security drone. I would like to build an AI that can use this code to control the car

**Comment by MysticNynja** [comment]
Same for me.
