### ISSUE TITLE
thermostat fan question

### ISSUE THREAD

**Issue by dhysom** [shauntarves/wyze-sdk#51]
Is there a way to turn the thermostat fan on/off independent of heating? The only choices appear to be AUTO, CYCLE, ON.

ON appears straight forward.
AUTO I assume means something like, "let the furnace decide" or "turn on when heating, possibly after a delay."
CYCLE I'm guessing is "run for X minutes hourly.

I haven't discovered (is it possible?) to turn the fan on/off independently of heating or cooling.

Thank you very much for your work on this project; it's great!

**Comment by shauntarves** [comment]
Hey @dhysom sorry it has taken me so long to address this.

I don't have access to a thermostat, but I'd be happy to fix this if you'd be willing to share your device with me (even just temporarily).

Let me know.

**Comment by shauntarves** [comment]
Closing due to lack of response. If a user is able to share a thermostat that is wired with fan controls, I'd be happy to look into this.
