### ISSUE TITLE
Support for Wyze Switch

### ISSUE THREAD

**Issue by TheGreatSkeeve** [shauntarves/wyze-sdk#66]
New product - https://wyze.com/wyze-light-switch.html

Is this already supported, and does it plan to be supported?

Thanks!

**Comment by shauntarves** [comment]
Hey @TheGreatSkeeve,

This would be an awesome addition. Hopefully it's pretty similar to the plug. I'd be happy to give this a go if you either a) want to send me a switch or b) don't mind sharing yours with my account for a little while so I can see how it's implemented.

Let me know. If it's easier to email, I'm shaun <at> tarves <dot> net

**Comment by JGirard8** [comment]
Hey @shauntarves 

If @TheGreatSkeeve hasn't been able to share a switch to you for testing, I'm more than happy to! Please let me know which account to share it to.

I'd love to be able to control the Wyze Switch via this SDK!

**Comment by TheGreatSkeeve** [comment]
@JGirard8 It's the same email he provided in his response. I did share it, but the share is listed as pending. Might not hurt to share yours!

**Comment by TheGreatSkeeve** [comment]
Dude, I think something got buggered on my end. I kid you not, I got three pop ups stating I'd shared stuff with you every time I opened the app - for like three weeks.

**Comment by shauntarves** [comment]
Hey guys, finally picking back up on this. I can still see @JGirard8 's switch, but only for limited actions (can't see schedule-related stuff).

I should be able to get some basic support in shortly. Thanks for everyone's patience.

**Comment by shauntarves** [comment]
@TheGreatSkeeve @JGirard8 

Hey all...I finally pushed up some support for the Switch on https://github.com/shauntarves/wyze-sdk/tree/66-support-for-wyze-switch. As I mentioned, I have very limited access on @JGirard8's Switch, so I can't model some of the more advanced features yet, but basic controls are there.

Some commands shown down below if you want to try it out. If there's any other functionality you want supported, let me know and we can figure something out.

```
did = 'LD_SS1_XXXX'
model = 'LD_SS1'

switch = client.switches.info(device_mac=did)
print(f"power: {switch.is_on}")
print(f"away mode: {switch.away_mode.value}")
if switch.timer_actions is not None:
    print(f"timer actions: {switch.timer_actions}")

print("Turning switch on...")
client.switches.turn_on(device_mac=did, device_model=model)
switch = client.switches.info(device_mac=did)
print(f"is on: {switch.is_on}")

print("Turning switch off...")
client.switches.turn_off(device_mac=did, device_model=model)
switch = client.switches.info(device_mac=did)
print(f"is on: {switch.is_on}")

print("Activating away mode...")
client.switches.set_away_mode(device_mac=did, device_model=model)
switch = client.switches.info(device_mac=did)
print(f"away mode: {switch.away_mode.value}")

print("Deactivating away mode...")
client.switches.set_away_mode(device_mac=did, device_model=model, away_mode=False)
switch = client.switches.info(device_mac=did)
print(f"away mode: {switch.away_mode.value}")

print("Turning switch off after 3 hours...")
client.switches.turn_on(device_mac=did, device_model=model)
client.switches.turn_off(device_mac=did, device_model=model, after=timedelta(hours=3))
client.switches.clear_timer(device_mac=did, device_model=model)

print("Turning switch on after 3 hours...")
client.switches.turn_off(device_mac=did, device_model=model)
client.switches.turn_on(device_mac=did, device_model=model, after=timedelta(hours=3))
client.switches.clear_timer(device_mac=did, device_model=model)
```

**Comment by shauntarves** [comment]
@TheGreatSkeeve @JGirard8 Last call for some testing on this, otherwise, I'll merge it to master tomorrow and create a new release.
