### ISSUE TITLE
How to access camera?

### ISSUE THREAD

**Issue by C4PT41ND34DP00L** [shauntarves/wyze-sdk#70]
I am struggling on how to access the cameras any help?

**Comment by TheGreatSkeeve** [comment]
Give this a go.

`import cv2
from wyze_sdk import Client
from dotenv import load_dotenv
import os
from datetime import *

load_dotenv()
username = os.getenv('wyze_email')
password = os.getenv('wyze_password')
client = Client(email=username, password=password)

cameras = {}
for cam in client.cameras.list():
    if cam.is_online == True:
        cameras[cam.nickname] = "rtsp://%s:%s@%s/live" % ("username", "password", cam.ip)

for key in cameras.keys():
    url = cameras[key]
    vcap = cv2.VideoCapture(url, cv2.CAP_FFMPEG)
    ret, frame = vcap.read()
    now = datetime.now()
    timestr = "{}-{}-{}-{}-{}".format(now.year, now.month, now.day, now.hour, now.minute)
    filename = 'snap-{}-{}.png'.format(key, timestr)
    cv2.imwrite(filename, frame)
`

**Comment by shauntarves** [comment]
@C4PT41ND34DP00L ,

Hopefully this gets you what you need in the short-term. Thanks to @TheGreatSkeeve for contributing this bit of code. I have hesitations about attempting to add camera support for a variety of reasons, mostly discussed in the other linked issues. I'm open to being swayed though!
