### ISSUE TITLE
Thanks for all your past work...  Any plans to address multi-level mapping for their Vac?

### ISSUE THREAD

**Issue by Jeppedy** [shauntarves/wyze-sdk#74]
I'd love to invoke my wyze robot vac when no one is home to be disturbed by it.  But I have the multi-map firmward.  Any chance you're still maintaining and advancing this project so we can automate the cleaning schedules of our Wyze Vacs?

Thanks for the considerations!!

J

**Comment by shauntarves** [comment]
Hi @Jeppedy I would love to give it a shot. I don't know if I've installed the multi-level firmware on my own vacs yet, but I can give it a try with at least one of them. I'll track this work in the existing issue #63

**Comment by shauntarves** [comment]
@Jeppedy this has been merged in for a while. Have you been able to investigate whether things are working with your installed firmware?
