### ISSUE TITLE
Does the Outdoor Plug report electric usage information?

### ISSUE THREAD

**Issue by tbenz9** [shauntarves/wyze-sdk#90]
The Wyze Outdoor Plug has the ability to track electricity consumption on a day/week/month basis.  Does the SDK retrieve that usage data?

**Comment by shauntarves** [comment]
It does not currently have that, but I can add that feature pretty easily!
Give me a few days and I'll update the ticket when it's ready.

Do you have any preference on what the shape of the data objects look like?
If you're an avid user of the energy monitoring feature in the app, you
would know far better than me how you'd want to use the data.

**Comment by tbenz9** [comment]
Wow, thank you for the reply and willingness to implement the feature.  The official Wyze App has no historical data for the energy usage.  At the end of every month the data is wiped and starts over from zero.  This makes it extremely difficult to compare 1 day/week/month to another to see trends.  My use case is simple, once an hour (or once a day) poll the plug and record the energy usage so I can see long-term trends, anomalies, etc.

Not sure it's really relevant to this ticket, but the Wyze forums have many posts complaining about the implementation of usage data in the official app.  [Here's one example.](https://forums.wyzecam.com/t/outdoor-plug-usage-history-should-not-reset-on-the-first-of-the-month/184303)

Thanks again, looking forward to seeing what you come up with.

**Comment by shauntarves** [comment]
@tbenz9 Hey there...I started playing around with this today. Even though the app only shows you the current month, it appears we can retrieve the last 30 days with the API. I'm guessing they purge "old" data after 30 days.

That said, I don't think it's in the best interest of this project to get into the business of storing data, but I'm happy to provide the API point and any kind of formatting options you think would be helpful. The way their data is transferred is pretty simple:
* For each device (plug or outdoor plug - and for the outdoor plug, BOTH sockets are reported together), you can request a list of records between a start date and end date
* There is one record **per day**, and the record contains a simple integer array with 24 elements
* Each element in the array represents the usage in Megawatt-hours for each hour of the day

That's all that is available. I've pushed up code to the `90-does-the-outdoor-plug-report-electric-usage-information` branch that will allow you to do this:

```
usage_records = client.plugs.get_usage_records(device_mac='xxxxxxx', start_time=datetime.now() - timedelta(days=5))
for _record in usage_records:
    print(_record.to_dict())

{'date': datetime.datetime(2022, 11, 3, 20, 0), 'hourly_data': [47, 50, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 51, 50]}
{'date': datetime.datetime(2022, 11, 4, 20, 0), 'hourly_data': [47, 50, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}
{'date': datetime.datetime(2022, 11, 5, 20, 0), 'hourly_data': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}
{'date': datetime.datetime(2022, 11, 6, 19, 0), 'hourly_data': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}
{'date': datetime.datetime(2022, 11, 7, 19, 0), 'hourly_data': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}
```

**Comment by tbenz9** [comment]
Wonderful!  I apologize if I led you astray, it's certainly not in the scope of this project to store the data.  My use case is to keep the data longer than 30 days, which I'll do by querying daily and storing elsewhere.

I'm completely satisfied with the data you've provided.  If I were to offer any minor suggestions it would be to offer a `daily_total` option so the user doesn't have to add all 24 values together.  But I can certainly do that on my end too.

Would you mind confirming the units used?  You mention "Megawatt-hours" which seems unlikely unless your plug us running a nuclear power plant.  Perhaps the correct unit is Watt-hours?

I haven't tried the branch yet, but I'll pull it down and give it a shot this week!

**Comment by tbenz9** [comment]
I haven't personally tested it yet, but It's all good with me!

**Comment by tbenz9** [comment]
I think you (and now I) actually made an interesting discovery.  The Indoor plugs have usage data too, but that usage data is not accessible anywhere in the official Wyze app as far as I can tell.  I did not know the indoor plugs tracked electrical usage data!

**Comment by shauntarves** [comment]
@tbenz9 I just pushed some new changes to handle both types of usage records. Unfortunately, it means you'll have to pass the device model into the call to get usage records:

```
client.plugs.get_usage_records(device_mac='XXXX', device_model='XXXX', start_time=datetime.now() - timedelta(days=10), end_time=datetime.now() - timedelta(days=5))
```

That will either return a list of `PlugUsageRecord` objects for indoor plugs (time-based usage measurements) or `PlugElectricityConsumptionRecord` for outdoor plugs (watt-hour usage). The `total_usage` property for each will return the appropriate values.

Let me know what you think

**Comment by tbenz9** [comment]
That sounds like an elegant and reasonable solution to me.  Thanks again!
