### ISSUE TITLE
Thermostat Room Sensors

### ISSUE THREAD

**Issue by jamespet77** [shauntarves/wyze-sdk#94]
Is is possible to get the data from the thermostat room sensors?

**Comment by shauntarves** [comment]
Hey @jamespet77, thanks for the question. I would love to add support for these! I didn't even know they existed until now.

So, what typically will happen with something like this is that I would need you to share the devices with me (temporarily) via the app. There is at least one open bug for the thermostat, so if you could share the sensor(s) and the thermostat, I can add support for this. My email for the Wyze account is shaun <at> tarves <dot> net

**Comment by jamespet77** [comment]
I can do that.  
just to confirm its shaun at tarves dot net

**Comment by shauntarves** [comment]
Yessir!

**Comment by jamespet77** [comment]
Sent.  It has one room sensor linked.  I have another room sensor if you need multiple.

**Comment by shauntarves** [comment]
@jamespet77 I've just pushed initial support for reading room sensor data to branch 94-thermostat-room-sensors

You can get a list of sensors connected to a thermostat by issuing:
```
sensors = client.thermostats.get_sensors(device_mac=<device_id>, device_model='CO_EA1')
```

The sensor object looks like this:
```
for _sensor in sensors:
    print(f"    id: {_sensor.did}")
    print(f"        name: {_sensor.nickname}")
    print(f"        temperature: {_sensor.temperature}")
    print(f"        humidity: {_sensor.humidity}")
    print(f"        battery: {_sensor.battery}")
    print(f"        state: {_sensor.state}")
    print(f"        status: {_sensor.status}")
    print(f"        auto_comfort_mode: {_sensor.auto_comfort_mode}")
    print(f"        comfort_balance_weight: {_sensor.comfort_balance_weight}")
    print(f"        temperature_threshold: {_sensor.temperature_threshold}")

id: CO_TH1_XXXX
        name: Kitchen
        temperature: 73.86
        humidity: 33
        battery: RoomSensorBatteryLevel.LEVEL_3
        state: RoomSensorStateType.ONLINE
        status: RoomSensorStatusType.MANUAL_UP
        auto_comfort_mode: ThermostatSensorTemplate.HOME_SLEEP
        comfort_balance_weight: ThermostatSensorComfortBalanceMode.BALANCE
        temperature_threshold: 5
```

**Comment by jamespet77** [comment]
Thanks Shaun!!  big help.  Wyze needsto put you on the team.

**Comment by shauntarves** [comment]
Give it a try and make sure it's working for your use cases. If so, I'll
merge to master and make a new release.

I'm going to use this opportunity to address
https://github.com/shauntarves/wyze-sdk/issues/51 and
https://github.com/shauntarves/wyze-sdk/issues/42 so might be a few days.
